### ISSUE TITLE
Reficio.org and releases

### ISSUE THREAD

**Issue by thegreystone** [reficio/p2-maven-plugin#140]
Dear maintainers,

We're using the p2-maven-plugin to build OpenJDK Mission Control, but Oracle is a bit antsy about letting us use this plug-in for two reasons:

1. Reficio.org seems gone.
2. There has not been a new release in over a year.

So I wonder:
1. Will reficio.org make a phoenix like re-appearance, or is it gone for good?
2. Will there eventually be another release of the p2-maven-plugin?
3. If so, will it still be under the reficio coordinates, or will this plug-in get new coordinates?

We're quite happy with the functionality of this plug-in. Let us know if there is anything we can do to help!

Kind regards,
Marcus

**Comment by tombujok** [comment]
Hey,

Happy you are using my p2-maven-plugin!

1.) Yes, it should re-appear in the next 48 or so. I have already paid for the domain. If you are in a hurry, you can use maven central: https://search.maven.org/search?q=p2-maven-plugin

2.) I'm not actively developing it anymore, but mainly due to the reason that it's pretty much feature complete. It's a small tool doing it's task, so I don't really see any big release coming up soon.
If you need anything I'm happy to accept a pull request and release a new version. 

3.) Under reficio & maven central

Hope it helps!
Best,
Tom

**Comment by thegreystone** [comment]
Hi Tom!

Good to hear about the re-appearance! It's not for actually getting the plug-in, it's more that the domain disappearing when we're trying to get third-party approval for using it is a little bit disconcerting. ;)

We may start contributing if we identify a need. Thank you!

Kind regards,
Marcus

**Comment by tombujok** [comment]
BTW, it's up:)
