### ISSUE TITLE
[ENH] Sanitize broken manifest in source bundles

### ISSUE THREAD

**Issue by emweber** [reficio/p2-maven-plugin#249]
Some artifacts on central are already OSGI-bundles, but their source-bundle mainfest is broken; i.e the source bundle claims to export the same packages as the bundle. This causes p2 to resolve to the source-bundle instead of the real bundle jar.

I found that the source bundle of `org.jboss.spec.javax.annotation:jboss-annotations-api_1.3_spec:2.0.1.Final` is broken.
Specifying the `<override>` option did not help to fix the source-bundle manifest.
It would be useful if the `<override>` option would also process the source bundle or if there is a separate option to force manifest re-generation for source bundles only.

**Comment by sparsick** [comment]
Hi @emweber,

IMHO the manifest of the source jar and the "normal" jar should be identical. Therefore, I would prefer the `<override>` option should override both manifest files (in source jar and in the normal jar). 

Do you want to create a PR for solving this issue?

**Comment by emweber** [comment]
Well, I forgot to explicitly mention that in case of `org.jboss.spec.javax.annotation:jboss-annotations-api_1.3_spec:2.0.1.Final`
the **bundle** jar has perfect OSGI-headers, so I do **not** want to override them.
Only the manifest of the **source bundle** is broken and needs to be re-written.

What if p2-maven-plugin would always automatically detect broken source-bundles and re-writes the manifest then?
WDYT?

**Comment by sparsick** [comment]
Hi @emweber,

your idea that p2 maven plugin could detect broken source-bundle is good. P2 Maven plugin could log a warning if it finds it. But I struggle with the rewriting the manifest automatically, because it fights only a symptom and fighting symptoms should be a conscious decision by the developer to rewrite the manifest. Nevertheless, I would prefer the `<override>` option should override both manifest files (in source jar and in the normal jar). Yes, in this case the bundle jar is fine, but from consistency reason the `<override>` option should always override both manifest (in source-jar and normal jar). In your case it would mean, that you have to "copy" the bnd instruction from the original one.

**Comment by emweber** [comment]
Hi Sandra,
the pull requests as a POC simply removes the Export-Package, Export-Service and Provide-Capability headers from an **existing** source-bundle manifest **before** the Eclipse-SourceBundle headers are written. No logging yet since I'm unsure what the message should look like.
While this does not fix the issue, it solves my use-case: Fix broken source bundle manifests. 
Maybe I should update the issue title?

**Comment by sparsick** [comment]
Hi @emweber, yes... please update the issue title.

**Comment by sparsick** [comment]
@emweber Thank you for your contribution. I released a new version 1.7.0. with your PR. So in the next hours it should be available on Maven Central.

**Comment by castortech** [comment]
Hi @emweber,

This is great and I just had a similar case, but wondering if there are any reasons why only removing the exports?
